name: Arch Linux Script Test

on: [push, pull_request]

jobs:
  test-install:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: System Update and Prep
        run: |
          pacman -Sy --noconfirm
          pacman -S --noconfirm curl

      - name: Test Base Stage (Dry Run)
        run: |
          bash install.sh base

      - name: Test Post Stage (Dry Run)
        run: |
          bash install.sh post
